name: Update Leaderboard and Resize Images

on:
  schedule:
    - cron: '0 */6 * * *'


jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies and run script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python bot.py          

      # - name: Check for changes
      #   id: check_changes
      #   run: |
      #     git diff --exit-code || echo "::set-output name=changes::true"

      # - name: Commit and Push Changes
      #   if: steps.check_changes.outputs.changes == 'true'
      #   run: |
      #     git pull
      #     git add .
      #     git commit -m "Updated leaderboard and resized images for Project 1."
      #     git remote set-url origin https://$API_TOKEN@github.com/mlsanigeria/AI-Hacktober-MLSA.git
      #     git push